# Generated by Django 5.0.7 on 2024-07-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('comedy', 'Comedy Shows'), ('workshops', 'Workshops'), ('meetups', 'Meetups'), ('music', 'Music Shows'), ('kids', 'Kids'), ('exhibitions', 'Exhibitions'), ('performances', 'Performances')], default='comedy', max_length=20),
        ),
    ]
