# Generated by Django 5.0.7 on 2024-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_delete_contactenquiry_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=200),
        ),
    ]
