# Generated by Django 5.0.7 on 2024-07-21 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.DeleteModel(
            name='RSVP',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
