# Generated by Django 5.0.7 on 2024-07-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='photo',
            field=models.ImageField(upload_to='static/contact_enquiry_photos/'),
        ),
    ]
