# Generated by Django 5.0.7 on 2024-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_remove_event_url_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
