# Generated by Django 5.0.7 on 2024-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactEnquiry',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
