# Generated by Django 5.0.7 on 2024-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(related_name='participants', to='eventapp.event'),
        ),
    ]
